// OrionPublicPacket.c was generated by ProtoGen version 2.12.c

#include "OrionPublicPacket.h"
#include "floatspecial.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"

/*!
 * \brief Encode a Date_t structure into a byte array
 *
 * Compresssed date format.
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

/*!
 * \brief Decode a Date_t structure from a byte array
 *
 * Compresssed date format.
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Encode a OrionCmd_t structure into a byte array
 *
 * Structure for holding a gimbal axis command
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

/*!
 * \brief Decode a OrionCmd_t structure from a byte array
 *
 * Structure for holding a gimbal axis command
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Encode a OrionLaserState_t structure into a byte array
 *
 * Per-laser state information.
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

/*!
 * \brief Decode a OrionLaserState_t structure from a byte array
 *
 * Per-laser state information.
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Create the GeolocateTelemetryCore packet
 *
 * This packet is transmitted at 10 Hz by the gimbal to communicate the
 * information needed to locate the gimbal and its imagery, to determine the
 * gimbal mode of operation, and to determine how the video output stream is
 * being shifted by the gimbal. This is the primary packet that users should
 * monitor to determine the gimbal status and populate user interfaces.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the GeolocateTelemetryCore packet
 *
 * This packet is transmitted at 10 Hz by the gimbal to communicate the
 * information needed to locate the gimbal and its imagery, to determine the
 * gimbal mode of operation, and to determine how the video output stream is
 * being shifted by the gimbal. This is the primary packet that users should
 * monitor to determine the gimbal status and populate user interfaces.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionPerformance packet
 *
 * Measurements related to stabilization performance. This packet is sent by the
 * gimbal 4 times per second.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionPerformance packet
 *
 * Measurements related to stabilization performance. This packet is sent by the
 * gimbal 4 times per second.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionDiagnostics packet
 *
 * Electrical diagnostic data for the Orion gimbal. This packet is sent by the
 * gimbal every 3 seconds.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionDiagnostics packet
 *
 * Electrical diagnostic data for the Orion gimbal. This packet is sent by the
 * gimbal every 3 seconds.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

//! Encode a ThreadLoading_t structure into a byte array

//! Encode a CoreLoading_t structure into a byte array

/*!
 * \brief Encode a ThreadLoading_t structure into a byte array
 *
 * Per-thread information, in order of priority (highest to lowest)
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

/*!
 * \brief Encode a CoreLoading_t structure into a byte array
 *
 * Per-Core CPU load information
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

//! Decode a ThreadLoading_t structure from a byte array

//! Decode a CoreLoading_t structure from a byte array

/*!
 * \brief Decode a ThreadLoading_t structure from a byte array
 *
 * Per-thread information, in order of priority (highest to lowest)
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Decode a CoreLoading_t structure from a byte array
 *
 * Per-Core CPU load information
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Create the OrionSoftwareDiagnostics packet
 *
 * Diagnostic information related to software performance for a specific board
 * in the Orion Gimbal. This packet is sent by the gimbal once per second.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionSoftwareDiagnostics packet
 *
 * Diagnostic information related to software performance for a specific board
 * in the Orion Gimbal. This packet is sent by the gimbal once per second.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

//! Encode a FftData_t structure into a byte array

/*!
 * \brief Encode a FftData_t structure into a byte array
 *
 * A series of points containing FFT-derived frequency and magnitude data
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

//! Decode a FftData_t structure from a byte array

/*!
 * \brief Decode a FftData_t structure from a byte array
 *
 * A series of points containing FFT-derived frequency and magnitude data
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Create the OrionVibration packet
 *
 * Platform vibration amplitude and frequency information. This packet is sent
 * by the gimbal once every five seconds.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionVibration packet
 *
 * Platform vibration amplitude and frequency information. This packet is sent
 * by the gimbal once every five seconds.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the NetworkDiagnostics packet
 *
 * Ethernet network diagnostic information
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the NetworkDiagnostics packet
 *
 * Ethernet network diagnostic information
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionRetractStatus packet
 *
 * Current gimbal retraction mechanism status. This is sent by the gimbal
 * regularly only if a retract system is installed.
 * \param pkt points to the packet which will be created by this function
 * \param Cmd is The current command being tracked by the retract mechanism
 * \param State is The retraction mechanism state
 * \param Pos is Current retract position in radians
 * \param Flags is GPIO status information flags
 */

/*!
 * \brief Decode the OrionRetractStatus packet
 *
 * Current gimbal retraction mechanism status. This is sent by the gimbal
 * regularly only if a retract system is installed.
 * \param pkt points to the packet being decoded by this function
 * \param Cmd receives The current command being tracked by the retract mechanism
 * \param State receives The retraction mechanism state
 * \param Pos receives Current retract position in radians
 * \param Flags receives GPIO status information flags
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the StareStart packet
 *
 * This packet is transmitted by the gimbal during step-stare operations to
 * indicate that the gimbal is staring and a step-stare image should be
 * acquired. The position data mark the *desired* location that the gimbal is
 * trying to stare at. The *actual* position can be computed by using the gimbal
 * position, quaternion, and pan and tilt angles to project the camera line of
 * sight until to the terrain model. Once the image has been acquired send a
 * ORION_PKT_STARE_ACK packet to tell the gimbal it can move to the next stare
 * point.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the StareStart packet
 *
 * This packet is transmitted by the gimbal during step-stare operations to
 * indicate that the gimbal is staring and a step-stare image should be
 * acquired. The position data mark the *desired* location that the gimbal is
 * trying to stare at. The *actual* position can be computed by using the gimbal
 * position, quaternion, and pan and tilt angles to project the camera line of
 * sight until to the terrain model. Once the image has been acquired send a
 * ORION_PKT_STARE_ACK packet to tell the gimbal it can move to the next stare
 * point.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionResetSource packet
 *
 * Reset information for a processor in the Orion Gimbal. This packet is
 * transmitted by each processor in the gimbal following its bootup
 * \param pkt points to the packet which will be created by this function
 * \param Vector is Interrupt vector for the last reset
 * \param Address is Program counter prior to the reset (not yet used)
 * \param sourceBoard is Enumeration defining which board in the gimbal generated this message
 */

/*!
 * \brief Decode the OrionResetSource packet
 *
 * Reset information for a processor in the Orion Gimbal. This packet is
 * transmitted by each processor in the gimbal following its bootup
 * \param pkt points to the packet being decoded by this function
 * \param Vector receives Interrupt vector for the last reset
 * \param Address receives Program counter prior to the reset (not yet used)
 * \param sourceBoard receives Enumeration defining which board in the gimbal generated this message
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the DebugString packet
 *
 * This packet sends a human readable text string which is typically used for
 * debugging purposes.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the DebugString packet
 *
 * This packet sends a human readable text string which is typically used for
 * debugging purposes.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the KlvUserData packet
 *
 * This packet is used to set and query the values of user-configurable KLV tags
 * \param pkt points to the packet which will be created by this function
 * \param Key is UAS Local Set key
 * \param SubKey is UAS Local Set sub-key, if applicable (e.g., security metadata)
 * \param Length is Data length, in bytes
 * \param Value is Variable-length value string
 */

/*!
 * \brief Decode the KlvUserData packet
 *
 * This packet is used to set and query the values of user-configurable KLV tags
 * \param pkt points to the packet being decoded by this function
 * \param Key receives UAS Local Set key
 * \param SubKey receives UAS Local Set sub-key, if applicable (e.g., security metadata)
 * \param Length receives Data length, in bytes
 * \param Value receives Variable-length value string
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the GpsData packet
 *
 * Raw GPS data. This packet is normally sent by the gimbal once per second,
 * unless the gimbal is in INS debug mode, in which case this packet is sent for
 * every GPS report. This packet can also be sent to the gimbal in order to
 * provide GPS information. Sending this packet to the gimbal will override any
 * internal GPS. The ideal rate to send this packet to the gimbal is 4Hz.
 *
 * Note that the position information of this packet is *not* the definitive
 * position of the gimbal. That information comes from the INS in the gimbal and
 * is visible in the GeolocateTelemetryCore packet.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the GpsData packet
 *
 * Raw GPS data. This packet is normally sent by the gimbal once per second,
 * unless the gimbal is in INS debug mode, in which case this packet is sent for
 * every GPS report. This packet can also be sent to the gimbal in order to
 * provide GPS information. Sending this packet to the gimbal will override any
 * internal GPS. The ideal rate to send this packet to the gimbal is 4Hz.
 *
 * Note that the position information of this packet is *not* the definitive
 * position of the gimbal. That information comes from the INS in the gimbal and
 * is visible in the GeolocateTelemetryCore packet.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the InsQuality packet
 *
 * This packet is transmitted once per second by the gimbal to communicate the
 * quality of the inertial navigation system (INS) data. The INS is responsible
 * for fusing the crown board IMU and GPS to determine the position, velocity,
 * attitude, and IMU errors. The quality of the INS data directly impacts the
 * quality of the data in the GeolocateTelemetryCore packet. This data are only
 * sent once per second as the quality data changes slowly.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the InsQuality packet
 *
 * This packet is transmitted once per second by the gimbal to communicate the
 * quality of the inertial navigation system (INS) data. The INS is responsible
 * for fusing the crown board IMU and GPS to determine the position, velocity,
 * attitude, and IMU errors. The quality of the INS data directly impacts the
 * quality of the data in the GeolocateTelemetryCore packet. This data are only
 * sent once per second as the quality data changes slowly.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionCmd packet
 *
 * Basic commands for control of gimbal pan and tilt. Send this packet to the
 * gimbal to effect basic pan and tilt control. The gimbal will echo the packet
 * as confirmation of receiving it. Note that this packet cannot be used to
 * command the Geopoint or Path modes; those modes need to be commanded through
 * their respective packets. If the gimbal is in Geopoint or Path mode receiving
 * this packet will cancel those modes.
 * \param pkt points to the packet which will be created by this function
 * \param Cmd is Pan/tilt command
 */

/*!
 * \brief Decode the OrionCmd packet
 *
 * Basic commands for control of gimbal pan and tilt. Send this packet to the
 * gimbal to effect basic pan and tilt control. The gimbal will echo the packet
 * as confirmation of receiving it. Note that this packet cannot be used to
 * command the Geopoint or Path modes; those modes need to be commanded through
 * their respective packets. If the gimbal is in Geopoint or Path mode receiving
 * this packet will cancel those modes.
 * \param pkt points to the packet being decoded by this function
 * \param Cmd receives Pan/tilt command
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionStartupCmd packet
 *
 * Command to run upon motor initialization
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionStartupCmd packet
 *
 * Command to run upon motor initialization
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionStartupCmd packet
 *
 * Command to run upon motor initialization
 * \param pkt points to the packet which will be created by this function
 * \param Cmd is Pan/tilt command. Defaults to position mode, pan/tilt of 0
 */

/*!
 * \brief Decode the OrionStartupCmd packet
 *
 * Command to run upon motor initialization
 * \param pkt points to the packet being decoded by this function
 * \param Cmd receives Pan/tilt command. Defaults to position mode, pan/tilt of 0
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

//! Encode a PosPreset_t structure into a byte array

/*!
 * \brief Encode a PosPreset_t structure into a byte array
 *

 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

//! Decode a PosPreset_t structure from a byte array

/*!
 * \brief Decode a PosPreset_t structure from a byte array
 *

 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Create the OrionPositions packet
 *
 * Stored gimbal positions
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionPositions packet
 *
 * Stored gimbal positions
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the GeopointCmd packet
 *
 * Send this packet to command the gimbal to go to Geopoint mode. In geopoint
 * the gimbal looks at a target as given by a latitude, longitude, altitude
 * position. The geopoint command can include a target velocity, which will
 * cause the gimbal to smoothly move its stare point as it propagates the target
 * position. Geopoint mode is canceled by sending a normal OrionCmd packet.
 * \param pkt points to the packet which will be created by this function
 * \param targetLat is Geodetic latitude of the target in radians, positive North
 * \param targetLon is Longitude of the target in radians, positive East
 * \param targetAlt is Altitude of the target in meters above the WGS-84 ellipsoid
 * \param targetVelNED is Velocity of the target in North, East, Down meters per second
 * \param joystickRange is Estimated range to target in meters. If non-zero *and* if geopoint is already running the position information in this packet is ignored and only the velocity and range information is used to propagate the geopoint command position. This is used for cases where a joystick is being used to drive the geopoint. If the gimbal has its own range estimate then a non-zero joystickRange will be replaced with the gimbal's internal range estimate. If you want the gimbal use the joystick mode but you cannot compute the range, use a range less than 10 meters and the gimbal will not do the range adjustment
 * \param options is Options for the geopoint packet.
 */

/*!
 * \brief Decode the GeopointCmd packet
 *
 * Send this packet to command the gimbal to go to Geopoint mode. In geopoint
 * the gimbal looks at a target as given by a latitude, longitude, altitude
 * position. The geopoint command can include a target velocity, which will
 * cause the gimbal to smoothly move its stare point as it propagates the target
 * position. Geopoint mode is canceled by sending a normal OrionCmd packet.
 * \param pkt points to the packet being decoded by this function
 * \param targetLat receives Geodetic latitude of the target in radians, positive North
 * \param targetLon receives Longitude of the target in radians, positive East
 * \param targetAlt receives Altitude of the target in meters above the WGS-84 ellipsoid
 * \param targetVelNED receives Velocity of the target in North, East, Down meters per second
 * \param joystickRange receives Estimated range to target in meters. If non-zero *and* if geopoint is already running the position information in this packet is ignored and only the velocity and range information is used to propagate the geopoint command position. This is used for cases where a joystick is being used to drive the geopoint. If the gimbal has its own range estimate then a non-zero joystickRange will be replaced with the gimbal's internal range estimate. If you want the gimbal use the joystick mode but you cannot compute the range, use a range less than 10 meters and the gimbal will not do the range adjustment
 * \param options receives Options for the geopoint packet.
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

//! Encode a Point_t structure into a byte array

/*!
 * \brief Encode a Point_t structure into a byte array
 *
 * List of path points
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

//! Decode a Point_t structure from a byte array

/*!
 * \brief Decode a Point_t structure from a byte array
 *
 * List of path points
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Create the OrionPath packet
 *
 * The path packet contains a series of waypoints that define a path in 3D
 * space. Sending this packet enables the path track logic, which will cause the
 * gimbal to look at the nearest point on the path; or look directly downward.
 * Path mode is canceled by sending a normal OrionCmd packet.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionPath packet
 *
 * The path packet contains a series of waypoints that define a path in 3D
 * space. Sending this packet enables the path track logic, which will cause the
 * gimbal to look at the nearest point on the path; or look directly downward.
 * Path mode is canceled by sending a normal OrionCmd packet.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the StareAck packet
 *
 * This packet tells the gimbal that the step-stare image has been acquired and
 * the gimbal can move to the next step stare point.
 * \param pkt points to the packet which will be created by this function
 * \param echoSystemTime is Milliseconds since system bootup received from ORION_PKT_STARE_START. If this value matches the value sent in ORION_PKT_STARE_START then the gimbal will terminate the stare operation early.
 */

/*!
 * \brief Decode the StareAck packet
 *
 * This packet tells the gimbal that the step-stare image has been acquired and
 * the gimbal can move to the next step stare point.
 * \param pkt points to the packet being decoded by this function
 * \param echoSystemTime receives Milliseconds since system bootup received from ORION_PKT_STARE_START. If this value matches the value sent in ORION_PKT_STARE_START then the gimbal will terminate the stare operation early.
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the GeoidUndulation packet
 *
 * Packet for periodic geoid undulation data uplink for GPS sources without a
 * geoid model
 * \param pkt points to the packet which will be created by this function
 * \param Undulation is 
 */

/*!
 * \brief Decode the GeoidUndulation packet
 *
 * Packet for periodic geoid undulation data uplink for GPS sources without a
 * geoid model
 * \param pkt points to the packet being decoded by this function
 * \param Undulation receives 
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionCameraSwitch packet
 *
 * Command the gimbal to swtich cameras.
 * \param pkt points to the packet which will be created by this function
 * \param Index is The index of the camera to switch to, counting from 0
 */

/*!
 * \brief Decode the OrionCameraSwitch packet
 *
 * Command the gimbal to swtich cameras.
 * \param pkt points to the packet being decoded by this function
 * \param Index receives The index of the camera to switch to, counting from 0
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionCameraState packet
 *
 * Command a camera in the gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param Zoom is Digital zoom ratio
 * \param Focus is Focus command/position
 * \param Index is The index of the camera to command
 */

/*!
 * \brief Decode the OrionCameraState packet
 *
 * Command a camera in the gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param Zoom receives Digital zoom ratio
 * \param Focus receives Focus command/position
 * \param Index receives The index of the camera to command
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionFlirSettings packet
 *
 * FLIR-specific camera settings.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionFlirSettings packet
 *
 * FLIR-specific camera settings.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionAptinaSettings packet
 *
 * Aptina-specific camera settings.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionAptinaSettings packet
 *
 * Aptina-specific camera settings.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionZafiroSettings packet
 *
 * Zafiro-specific camera settings.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionZafiroSettings packet
 *
 * Zafiro-specific camera settings.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionHitachiSettings packet
 *
 * Hitachi-specific camera settings.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionHitachiSettings packet
 *
 * Hitachi-specific camera settings.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionSonySettings packet
 *
 * Sony-specific camera settings.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionSonySettings packet
 *
 * Sony-specific camera settings.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionKtncSettings packet
 *
 * KTnC-specific camera settings.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionKtncSettings packet
 *
 * KTnC-specific camera settings.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionRetractCommand packet
 *
 * Retract or deploy command for a gimbal retraction mechanism.
 * \param pkt points to the packet which will be created by this function
 * \param Cmd is The retraction mechanism command
 */

/*!
 * \brief Decode the OrionRetractCommand packet
 *
 * Retract or deploy command for a gimbal retraction mechanism.
 * \param pkt points to the packet being decoded by this function
 * \param Cmd receives The retraction mechanism command
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionUserData packet
 *
 * This packet can be used to transfer user-defined data payloads between
 * communication ports on the gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionUserData packet
 *
 * This packet can be used to transfer user-defined data payloads between
 * communication ports on the gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionLaserCommand packet
 *
 * Command to fire the laser (if installed).
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionLaserCommand packet
 *
 * Command to fire the laser (if installed).
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionLaserStates packet
 *
 * Information about the current state of lasers installed in the gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionLaserStates packet
 *
 * Information about the current state of lasers installed in the gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionUartConfig packet
 *
 * This packet is used to change or request the baud rate and protocol of a UART
 * on the crown board. Send this packet with zero bytes to request the
 * configuration of the port that receives the request, or with 1 byte to
 * request the configuration of a specific port. Not all port configuration
 * options are available, the ethernet port must run the PROTOCOL_ORION protocol
 * at either 115200 or 230400 bits per second. In general users should not
 * change the ethernet port setup. In addition the PROTOCOL_UBLOX_GPS is not
 * supported on any user configurable port, it is included in the protocol list
 * only for completeness.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionUartConfig packet
 *
 * This packet is used to change or request the baud rate and protocol of a UART
 * on the crown board. Send this packet with zero bytes to request the
 * configuration of the port that receives the request, or with 1 byte to
 * request the configuration of a specific port. Not all port configuration
 * options are available, the ethernet port must run the PROTOCOL_ORION protocol
 * at either 115200 or 230400 bits per second. In general users should not
 * change the ethernet port setup. In addition the PROTOCOL_UBLOX_GPS is not
 * supported on any user configurable port, it is included in the protocol list
 * only for completeness.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionLimitsData packet
 *
 * Gimbal limits of operation. This includes the max and min pan and tilt
 * angles, as well as the angular rate and the maximum current consumption.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionLimitsData packet
 *
 * Gimbal limits of operation. This includes the max and min pan and tilt
 * angles, as well as the angular rate and the maximum current consumption.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the InsOptions packet
 *
 * INS options give configuration options for the inertial navigation system
 * (INS) in the gunbal. Changing the INS options will cause the INS to be
 * restarted if the platform rotation changes. When using platform rotation note
 * the order: First yaw about the gimbal's z-axis to create an intermediate
 * axis. Then pitch about the intermediate y-axis to create a second
 * intermediate axis. Finally roll about the second intermediate x-axis to reach
 * the platform orientation. When using an IMU in the payload ball the
 * enablePlatformRotation can still be used, but will only effect heading
 * observations and the GPS lever arm, it will not rotate the IMU data.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the InsOptions packet
 *
 * INS options give configuration options for the inertial navigation system
 * (INS) in the gunbal. Changing the INS options will cause the INS to be
 * restarted if the platform rotation changes. When using platform rotation note
 * the order: First yaw about the gimbal's z-axis to create an intermediate
 * axis. Then pitch about the intermediate y-axis to create a second
 * intermediate axis. Finally roll about the second intermediate x-axis to reach
 * the platform orientation. When using an IMU in the payload ball the
 * enablePlatformRotation can still be used, but will only effect heading
 * observations and the GPS lever arm, it will not rotate the IMU data.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionNetworkSettings packet
 *
 * Change the IP network settings in the gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionNetworkSettings packet
 *
 * Change the IP network settings in the gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionNetworkByteSettings packet
 *
 * Change the IP network settings in the gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionNetworkByteSettings packet
 *
 * Change the IP network settings in the gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionNetworkVideo packet
 *
 * Change the IP settings for video delivery.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionNetworkVideo packet
 *
 * Change the IP settings for video delivery.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionNetworkByteVideo packet
 *
 * Change the IP settings for video delivery.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionNetworkByteVideo packet
 *
 * Change the IP settings for video delivery.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

//! Encode a OrionCamSettings_t structure into a byte array

/*!
 * \brief Encode a OrionCamSettings_t structure into a byte array
 *
 * Camera settings information
 * \param data points to the byte array to add encoded data to
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of encoded bytes.
 * \param user is the data to encode in the byte array
 */

//! Decode a OrionCamSettings_t structure from a byte array

/*!
 * \brief Decode a OrionCamSettings_t structure from a byte array
 *
 * Camera settings information
 * \param data points to the byte array to decoded data from
 * \param bytecount points to the starting location in the byte array, and will be incremented by the number of bytes decoded
 * \param user is the data to decode from the byte array
 * \return 1 if the data are decoded, else 0. If 0 is returned bytecount will not be updated.
 */

/*!
 * \brief Create the OrionCameras packet
 *
 * Camera definitions for the Orion gimbal
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionCameras packet
 *
 * Camera definitions for the Orion gimbal
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionClevisVersion packet
 *
 * Software version for the clevis board in the Orion gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionClevisVersion packet
 *
 * Software version for the clevis board in the Orion gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionCrownVersion packet
 *
 * Software version for the crown board in the Orion gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionCrownVersion packet
 *
 * Software version for the crown board in the Orion gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionPayloadVersion packet
 *
 * Software version for the payload board in the Orion gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionPayloadVersion packet
 *
 * Software version for the payload board in the Orion gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionTrackerVersion packet
 *
 * Software version for the tracker board in the Orion Gimbal (if applicable)
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionTrackerVersion packet
 *
 * Software version for the tracker board in the Orion Gimbal (if applicable)
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionTrackerVersion packet
 *
 * Software version for the tracker board in the Orion Gimbal (if applicable)
 * \param pkt points to the packet which will be created by this function
 * \param Version is Version of the tracker board software
 * \param PartNumber is Hardware details of the tracker board
 * \param AppBits is Tracker application license bitfield
 */

/*!
 * \brief Decode the OrionTrackerVersion packet
 *
 * Software version for the tracker board in the Orion Gimbal (if applicable)
 * \param pkt points to the packet being decoded by this function
 * \param Version receives Version of the tracker board software
 * \param PartNumber receives Hardware details of the tracker board
 * \param AppBits receives Tracker application license bitfield
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionRetractVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionRetractVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionRetractVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet which will be created by this function
 * \param Version is Version of the retract board software
 */

/*!
 * \brief Decode the OrionRetractVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet being decoded by this function
 * \param Version receives Version of the retract board software
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionLensCtlVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionLensCtlVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionLensCtlVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet which will be created by this function
 * \param Version is Version of the retract board software
 */

/*!
 * \brief Decode the OrionLensCtlVersion packet
 *
 * Software version for the retract board in the Retract Unit (if applicable)
 * \param pkt points to the packet being decoded by this function
 * \param Version receives Version of the retract board software
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionBoard packet
 *
 * Information for a specific board in the gimbal.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionBoard packet
 *
 * Information for a specific board in the gimbal.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionAutopilotData packet
 *
 * Autopilot state data. The gimbal will use this information to limit certain
 * operations, for example some lasers will not fire unless the autopilot is
 * flying with sufficient altitude above ground.
 * \param pkt points to the packet which will be created by this function
 * \param user points to the user data that will be encoded in pkt
 */

/*!
 * \brief Decode the OrionAutopilotData packet
 *
 * Autopilot state data. The gimbal will use this information to limit certain
 * operations, for example some lasers will not fire unless the autopilot is
 * flying with sufficient altitude above ground.
 * \param pkt points to the packet being decoded by this function
 * \param user receives the data decoded from the packet
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionExtHeadingData packet
 *
 * Externally supplied heading information. Send this packet to supply a
 * correction to the heading of the inertial navigation system of the gimbal.
 * This packet will be echoed back to the user if INS logging is enabled.
 * \param pkt points to the packet which will be created by this function
 * \param extHeading is External true heading observation in radians from -pi to pi
 * \param noise is Sensor noise of the heading observation in radians. Send 0 to cause the INS to simply shift its heading. Otherwise the extHeading will be fed into the INS kalman filter with this sensor noise.
 * \param headingInGimbalAxis is Set this if the provided heading is in gimbal native axis rather than the platform axis. This will cause the gimbal to rotate the heading reference as needed to the platform axis used by the INS. This will have no effect if the INS options do not specify a platform rotation.
 * \param headingFromAlign is Set this if the provided heading came from an align system.
 * \param pitch is Pitch angle in radians from -pi to pi of the vector used to compute heading.
 */

/*!
 * \brief Decode the OrionExtHeadingData packet
 *
 * Externally supplied heading information. Send this packet to supply a
 * correction to the heading of the inertial navigation system of the gimbal.
 * This packet will be echoed back to the user if INS logging is enabled.
 * \param pkt points to the packet being decoded by this function
 * \param extHeading receives External true heading observation in radians from -pi to pi
 * \param noise receives Sensor noise of the heading observation in radians. Send 0 to cause the INS to simply shift its heading. Otherwise the extHeading will be fed into the INS kalman filter with this sensor noise.
 * \param headingInGimbalAxis receives Set this if the provided heading is in gimbal native axis rather than the platform axis. This will cause the gimbal to rotate the heading reference as needed to the platform axis used by the INS. This will have no effect if the INS options do not specify a platform rotation.
 * \param headingFromAlign receives Set this if the provided heading came from an align system.
 * \param pitch receives Pitch angle in radians from -pi to pi of the vector used to compute heading.
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */

/*!
 * \brief Create the OrionRangeData packet
 *
 * Ranging information from the gimbal to its target. The gimbal will use this
 * information to compute the target location and populate that informtaion in
 * its telemetry output.
 * \param pkt points to the packet which will be created by this function
 * \param range is Range to target in meters
 * \param maxAgeMs is Maximum data age before expiration in milliseconds
 * \param source is Source of range information
 */

/*!
 * \brief Decode the OrionRangeData packet
 *
 * Ranging information from the gimbal to its target. The gimbal will use this
 * information to compute the target location and populate that informtaion in
 * its telemetry output.
 * \param pkt points to the packet being decoded by this function
 * \param range receives Range to target in meters
 * \param maxAgeMs receives Maximum data age before expiration in milliseconds
 * \param source receives Source of range information
 * \return 0 is returned if the packet ID or size is wrong, else 1
 */
// end of OrionPublicPacket.c
