FROM gapsclosure/closuredev:develop

RUN sudo apt update -y \
&&  sudo apt install -y cmake software-properties-common
RUN sudo apt install -y libmbedtls-dev
RUN sudo apt install -y zlib1g-dev liblzma-dev libbz2-dev \
libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev \
libavdevice-dev libpostproc-dev libswscale-dev libswresample-dev

